USE DATABASE USERS_DB;
USE SCHEMA PESTYL;



-- CREATE FILE FORMAT FOR STAGE
-- DON'T SKIP HEADER TO PREVIEW THE COLUMN NAMMES
CREATE OR REPLACE FILE FORMAT csv_file
    TYPE = csv
    FIELD_DELIMITER = ','
    SKIP_HEADER = 0;

    
-- CREATE STAGE TO DATA LOCATION
-- USE FILE_FORMAT
CREATE OR REPLACE STAGE time_travel_stage
    URL = 's3://data-snowflake-fundamentals/time-travel/'
    FILE_FORMAT = csv_file;

    
-- VIEW DATA IN STAGE ON S3
LIST @time_travel_stage;


-- VIEW THE STAGED DATA WITHOUT CREATING A TABLE
-- SKIP HEADER = 0 WILL BE APPLIED ENALBING TO SEE THE COLUMN ROWS
SELECT $1, $2, $3, $4, $5, $6 
FROM @time_travel_stage 
LIMIT 10;


-- CREATE THE SNOWFLAKE TABLE USING THE COLUMN NAMES
CREATE OR REPLACE TABLE TIMETRAVEL(
    ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    GENEDER STRING,
    JOB STRING,
    PHONE STRING
);


-- MODIFY THE SKIP_HEADER TO START AT ROWS 2
ALTER FILE FORMAT csv_file SET SKIP_HEADER = 1;


-- VALIDATE COPY INTO FIRST
COPY INTO timetravel
    FROM @time_travel_stage
    VALIDATION_MODE='RETURN_5_ROWS';

    
-- NO DATA WAS LOADED WITH VALIDATION MODE
SELECT * FROM timetravel;


-- FULLY COPY DATA INTO TABLE
COPY INTO timetravel
    FROM @time_travel_stage;


-- PREVIEW TABLE
SELECT * FROM timetravel LIMIT 10;


-- DELETE TABLE
TRUNCATE TABLE timetravel;


    